<?php
require_once("financialFunctions.php");
require_once("resources/version.php");
define('HOSTNAME','localhost');
define('USERNAME','usernamehere');
define('UPDATEUSER','usernamehere');
define('UPDATEPASSWORD','yourpasswordhere');
define('PASSWORD','yourpasswordhere');
define('DATABASENAME','putyourdbnamehere');
define('ACCOUNTS','accounts');
define('TRANSACTIONS','transactions');
define('BILLS','bills');
define('PREFIX','wp_');
?>